name: struct
description: Library for packing and unpacking byte data using format strings
author: Austin Cummings <austincummings95@gmail.com>
homepage: https://github.com/austincummings/struct.dart
version: 1.0.0
dependencies:
  test: ">=0.12.4 <0.13.0"
